services:
  imd-travel:
    build: ../IMDTravel 
    ports:
      - "8080:8080"
    networks:
      - tolerancia_falhas_network
  
  fidelity:
    build: ../Fidelity
    ports:
      - "8081:8081"
    networks:
      - tolerancia_falhas_network

  exchange:
    build: ../Exchange
    ports:
      - "8082:8082"
    networks:
      - tolerancia_falhas_network

  airlines-hub:
    build: ../AirlinesHub
    ports:
      - "8083:8083"
    networks:
      - tolerancia_falhas_network

networks:
  tolerancia_falhas_network: