services:
  imd-travel:
    build: ../IMDTravel 
    ports:
      - "8080:8080"
    networks:
      - tolerancia_falhas_network
  
  fidelity:
    build: ../Fidelity
    ports:
      - "8081:8081"
    networks:
      - tolerancia_falhas_network

  exchange:
    build: ../Exchange
    ports:
      - "8082:8082"
    networks:
      - tolerancia_falhas_network

  airlines-hub:
    build: ../AirlinesHub
    ports:
      - "8083:8083"
    networks:
      - tolerancia_falhas_network

  k6:
    image: grafana/k6:latest
    container_name: k6-tf
    networks:
      - tolerancia_falhas_network
    ports:
      - "6565:6565"
      - "5665:5665"
    environment:
      - K6_WEB_DASHBOARD=true
    volumes:
      - ./k6:/scripts

networks:
  tolerancia_falhas_network: